name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          auto-update-conda: false
          channels: andrsd,main
          channel-priority: strict

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          conda install \
            cmake \
            make \
            automake \
            clangxx \
            fmt==9.1.0 \
            lcov

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DGMSHPARSERCPP_BUILD_TESTS=YES \
            -DGMSHPARSERCPP_CODE_COVERAGE=YES

      - name: Build
        run: make -C ${{ github.workspace }}/build

      - name: Run tests
        run: |
          ${{ github.workspace }}/build/test/gmshparsercpp-test \
            --gtest_output=xml:${{ github.workspace }}/build/gtest-results.xml

      - name: Test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: ${{ github.workspace }}/build/gtest-results.xml
          show: "fail, skip"

      - name: Upload test results to codecov.io
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ github.workspace }}/build/gtest-results.xml
          name: ${{ matrix.os }}

      - name: Generate code coverage
        if: startsWith(matrix.os, 'ubuntu')
        run: make -C ${{ github.workspace }}/build coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: coverage-${{ matrix.os }}
          path: ${{ github.workspace }}/build/coverage.info

  upload-to-codecov:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: "coverage-ubuntu-22.04/coverage.info"
