name: qa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clang-format style check
      uses: jidicula/clang-format-action@v4.3.0
      with:
        clang-format-version: '14'
        check-path: .

    - name: Check SPDX license lines
      uses: kt3k/license_checker@v1.0.6
